spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DEV_HOST:localhost}:${MYSQL_DEV_PORT:3306}/${MYSQL_DEV_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_DEV_USER}
    password: ${MYSQL_DEV_PASS}
    tomcat:
      initial-size: 5
#    initialization-mode: always

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: auto
      hibernate:
        dialect:  org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create-drop