spring:
  flyway.locations: classpath:db/migration/mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${MYSQL_TEST_PORT:3306}/test
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: none
    database: mysql