spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DEV_HOST:localhost}:${MYSQL_DEV_PORT:3306}/${MYSQL_DEV_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_DEV_USER}
    password: ${MYSQL_DEV_PASS}
    tomcat:
      initial-size: 5
    initialization-mode: always

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: auto
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
rsa:
  config:
    private-path: keys/rsa.private
    public-path: keys/rsa.public
    private-header: PRIVATE
    public-header: PUBLIC
jwt:
  prefix: Bearer
  expiration-in-min: 90
  contentType: application/json
  authorities: authorities